target  :testeSpecta do
  pod 'AFNetworking', :inhibit_warnings => true
end 

target  :testeSpectaTests do
  	pod 'Specta', :inhibit_warnings => true
  	pod 'Expecta'
	pod 'OCMock'
	pod 'TLJsonFactory'
end
